# =========================================================
#         S H _ D E M O _ S E T T I N G S . T O M L
# ---------------------------------------------------------
# Please see README.md for instructions on how to use 
# these settings and their effects
# =========================================================

# -- Misc. Settings for Data Management -------------------
UNIT_TEMPS = "C"        # [C|F|K]

# -- Misc. Application Defaults ---------------------------
# - Logger -
LOGFILE = "f451-sh-demo.log"
LOGLVL = 30             # 10 - DEBUG, 20 - INFO, 30 - WARNING, 40 - ERROR, 50 - CRITICAL       

# - Enviro -
ROTATION = 180          # [0, 90, 180, 270] - default rotation for Enviro+ LCD
DISPLAY = 0             # Default display mode
PROGRESS = 0            # [0|1] - 1 = show upload progress bar on LCD
SLEEP = 600             # Delay in seconds until screen is blanked

# - Other -
FREQ = 600              # Delay in seconds between uploads to cloud
DELAY = 300             # Delay in seconds before first upload to cloud
WAIT = 1                # Delay in seconds between sensor reads
THROTTLE = 120          # Additional delay in seconds on 'ThottlingError'
ROUNDING = 1            # Precision (num decimals) for uploaded data

TEMP_COMP = 0           # 0 = Disable temp compensation, >0 to be used comp.factor